version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "2020:8000"
    volumes:
      - .:/app
      - static_data:/app/static
      - media_data:/app/media
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/reezy
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reezy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    restart: always
    command: celery -A main_tasks worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/reezy
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
  celery-beat:
    build: .
    restart: always
    command: celery -A main_tasks beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/reezy
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
  static_data:
  media_data:
